#!/usr/bin/env node
/* Counts the only number that says whether skillfile worked: public repos that
 * carry a real, generated SKILLFILE.md and are NOT owned by the author.
 *
 * Stars are vanity, and npm downloads in the first fortnight are mostly
 * registry mirrors and scanners. An adopted convention shows up as strangers'
 * repos carrying the artifact, so that is what this counts.
 *
 *   node scripts/k-metric.js            print the current count
 *   node scripts/k-metric.js --append   also append a dated row to k-history.jsonl
 *
 * Two things this deliberately does NOT do:
 *
 * 1. Trust the filename. `filename:SKILLFILE.md` matches 20 repos today and not
 *    one is an adoption — they are game skill tables, SDK docs and generated
 *    TypeScript API pages called SkillFile.md. Every hit is fetched and checked
 *    for the generated marker before it counts.
 * 2. Rely on content search. GitHub's code index does not carry a phrase query
 *    for a repo this new (a marker search scoped to d08m/skillfile returns zero
 *    while the file plainly exists), so filename-then-verify is the only route
 *    that works from day one.
 */
const fs = require('fs');
const path = require('path');

const OWNER = 'd08m';
const MARKER = 'skillfile.pro';
const HISTORY = path.join(__dirname, '..', 'k-history.jsonl');

function token() {
  if (process.env.GITHUB_TOKEN) return process.env.GITHUB_TOKEN.trim();
  const envPath = 'C:/Users/domka/Desktop/foundry/.env';
  if (!fs.existsSync(envPath)) return null;
  const m = fs.readFileSync(envPath, 'utf8').match(/^GITHUB_TOKEN\s*=\s*"?([^"\r\n]+)"?/m);
  return m ? m[1].trim() : null;
}

async function gh(url, tok, raw) {
  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${tok}`,
      Accept: raw ? 'application/vnd.github.raw' : 'application/vnd.github+json',
      'User-Agent': 'skillfile-k-metric',
    },
  });
  if (!res.ok) return null;
  return raw ? res.text() : res.json();
}

(async () => {
  const tok = token();
  if (!tok) {
    console.error('k-metric: no GITHUB_TOKEN found.');
    process.exit(1);
  }

  const candidates = new Map(); // full_name -> {owner, path}
  for (let page = 1; page <= 5; page++) {
    const j = await gh(
      `https://api.github.com/search/code?q=${encodeURIComponent('filename:SKILLFILE.md')}&per_page=100&page=${page}`,
      tok
    );
    if (!j || !j.items || !j.items.length) break;
    for (const it of j.items) {
      const key = `${it.repository.full_name}:${it.path}`;
      candidates.set(key, {
        repo: it.repository.full_name,
        owner: it.repository.owner.login,
        path: it.path,
      });
    }
    if (j.items.length < 100) break;
  }

  const adopters = [];
  let mine = 0;
  let checked = 0;

  for (const c of candidates.values()) {
    const body = await gh(
      `https://api.github.com/repos/${c.repo}/contents/${encodeURI(c.path)}`,
      tok,
      true
    );
    checked++;
    if (!body || !body.includes(MARKER)) continue;
    if (c.owner.toLowerCase() === OWNER) { mine++; continue; }
    adopters.push(c.repo);
  }

  // Self-test. Our own repo carries the marker, so if the index cannot see it,
  // a K of 0 means "GitHub has not indexed anything yet", not "nobody adopted".
  // Without this the kill gate could fire on an artefact of the search index.
  const indexed = [...candidates.values()].some((c) => c.owner.toLowerCase() === OWNER);

  const k = new Set(adopters).size;
  console.log(`k-metric  ${new Date().toISOString().slice(0, 10)}`);
  console.log(`  files named SKILLFILE.md   : ${candidates.size}`);
  console.log(`  actually generated by us   : ${mine + adopters.length}  (checked ${checked})`);
  console.log(`  owned by ${OWNER}             : ${mine}`);
  console.log(`  K — stranger adoptions     : ${k}`);
  if (k) {
    console.log('\n  adopters:');
    for (const r of new Set(adopters)) console.log(`    https://github.com/${r}`);
  } else {
    console.log('\n  no stranger adoptions yet.');
  }

  if (!indexed) {
    console.log('\n  ⚠ d08m/skillfile is NOT in the search index yet, so this');
    console.log('    number is not yet trustworthy. Do not read a 0 as a real');
    console.log('    absence, and do not fire the kill gate, until this line');
    console.log('    disappears.');
  }

  if (process.argv.includes('--append')) {
    fs.appendFileSync(
      HISTORY,
      JSON.stringify({
        date: new Date().toISOString().slice(0, 10),
        candidates: candidates.size,
        generated: mine + adopters.length,
        k,
        adopters: [...new Set(adopters)],
      }) + '\n'
    );
    console.log(`\nappended to ${path.basename(HISTORY)}`);
  }
})().catch((e) => {
  console.error('k-metric failed:', e.message);
  process.exit(1);
});
