const fs = require('fs');
const path = require('path');
const { scanRepo } = require('./scanner');
const { renderSkillfileManifest, contentFingerprint } = require('./render');
const { resolveTargets, readEnabledTools, knownTargetIds } = require('./targets');

const SKILLFILE_MARKER = '<!-- skillfile:generated -->';
const MANIFEST = 'SKILLFILE.md';

function manifestPath(cwd) {
  return path.join(cwd, MANIFEST);
}

/** Opt-in targets are remembered in SKILLFILE.md so a bare `update`/`check`
 * — which is what CI runs — keeps writing the same set as the last `init`. */
function persistedTools(cwd) {
  const file = manifestPath(cwd);
  if (!fs.existsSync(file)) return [];
  return readEnabledTools(fs.readFileSync(file, 'utf8'));
}

function writeAll(cwd, toolIds) {
  const scan = scanRepo(cwd);
  const targets = resolveTargets(toolIds, scan);

  for (const target of targets) {
    const dest = path.join(cwd, target.dest);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, target.render());
  }
  fs.writeFileSync(manifestPath(cwd), renderSkillfileManifest(scan, targets));

  return { scan, targets };
}

/** Refuse to clobber anything a human wrote. Applies to every enabled target,
 * not just AGENTS.md — CLAUDE.md in particular is usually hand-written. */
function handWrittenTargets(cwd, targets) {
  return targets.filter((target) => {
    const dest = path.join(cwd, target.dest);
    if (!fs.existsSync(dest)) return false;
    return !fs.readFileSync(dest, 'utf8').includes(SKILLFILE_MARKER);
  });
}

/** Shared by init and update: `update` can widen the target set via --tools
 * too, so it needs the same protection — otherwise adding claude-md to a repo
 * with a hand-written CLAUDE.md would silently destroy it. */
function refuseOnConflicts(cwd, targets, force) {
  if (force) return false;
  const conflicts = handWrittenTargets(cwd, targets);
  if (!conflicts.length) return false;
  console.error(
    `The following files already exist and weren't generated by skillfile:\n` +
      conflicts.map((t) => `  ${t.dest}`).join('\n') +
      `\nRefusing to overwrite hand-written files. Re-run with --force to overwrite anyway.`
  );
  process.exitCode = 1;
  return true;
}

function init(cwd, opts = {}) {
  let targets;
  try {
    targets = resolveTargets(opts.tools, scanRepo(cwd));
  } catch (err) {
    console.error(`skillfile: ${err.message}`);
    process.exitCode = 1;
    return null;
  }

  if (refuseOnConflicts(cwd, targets, opts.force)) return null;

  const written = writeAll(cwd, opts.tools);
  console.log(`skillfile: generated context for "${written.scan.repoName}"\n`);
  for (const target of written.targets) console.log(`  ${target.dest}`);
  console.log(`  ${MANIFEST}\n`);
  console.log(`Commit these files. Run \`skillfile update\` after structural changes,`);
  console.log(`or \`skillfile check\` in CI to catch drift before it merges.`);
  return written;
}

function update(cwd, opts = {}) {
  const toolIds = [...persistedTools(cwd), ...(opts.tools || [])];
  let written;
  try {
    if (refuseOnConflicts(cwd, resolveTargets(toolIds, scanRepo(cwd)), opts.force)) return null;
    written = writeAll(cwd, toolIds);
  } catch (err) {
    console.error(`skillfile: ${err.message}`);
    process.exitCode = 1;
    return null;
  }
  console.log(`skillfile: updated context for "${written.scan.repoName}" (${written.targets.length} target(s))`);
  return written;
}

function check(cwd) {
  const file = manifestPath(cwd);
  if (!fs.existsSync(file)) {
    console.error('skillfile: not initialized in this repo. Run `skillfile init` first.');
    process.exitCode = 2;
    return;
  }

  const existing = fs.readFileSync(file, 'utf8');
  const hashMatch = existing.match(/source-hash:\s*([a-f0-9]+)/);
  const existingHash = hashMatch ? hashMatch[1] : null;

  const scan = scanRepo(cwd);
  const targets = resolveTargets(readEnabledTools(existing), scan);

  // A declared target that no longer exists on disk is drift too — someone
  // deleted a generated file without re-running update.
  const missing = targets.filter((t) => !fs.existsSync(path.join(cwd, t.dest)));
  if (missing.length) {
    console.error(
      `skillfile: declared target(s) missing from the repo:\n` +
        missing.map((t) => `  ${t.dest}`).join('\n') +
        `\nRun \`skillfile update\` and commit the result.`
    );
    process.exitCode = 1;
    return;
  }

  if (existingHash === contentFingerprint(scan)) {
    console.log(`skillfile: up to date (${targets.length} target(s)).`);
    process.exitCode = 0;
    return;
  }

  console.error(
    `skillfile: generated context is stale (repo has drifted since last generation).\n` +
      `Run \`skillfile update\` and commit the result.`
  );
  process.exitCode = 1;
}

module.exports = { init, update, check, writeAll, knownTargetIds, SKILLFILE_MARKER };
