const fs = require('fs');
const path = require('path');
const { scanRepo } = require('./scanner');
const { renderAgentsMd, renderSkillMd, renderSkillfileManifest, contentFingerprint } = require('./render');

const SKILLFILE_MARKER = '<!-- skillfile:generated -->';

function outputPaths(cwd, repoName) {
  return {
    agentsMd: path.join(cwd, 'AGENTS.md'),
    skillMd: path.join(cwd, '.claude', 'skills', repoName, 'SKILL.md'),
    skillfileManifest: path.join(cwd, 'SKILLFILE.md'),
  };
}

function writeAll(cwd) {
  const scan = scanRepo(cwd);
  const paths = outputPaths(cwd, scan.repoName);

  fs.mkdirSync(path.dirname(paths.skillMd), { recursive: true });
  fs.writeFileSync(paths.agentsMd, renderAgentsMd(scan));
  fs.writeFileSync(paths.skillMd, renderSkillMd(scan));
  fs.writeFileSync(paths.skillfileManifest, renderSkillfileManifest(scan));

  return { scan, paths };
}

function init(cwd, opts = {}) {
  const agentsMdPath = path.join(cwd, 'AGENTS.md');
  if (fs.existsSync(agentsMdPath) && !opts.force) {
    const existing = fs.readFileSync(agentsMdPath, 'utf8');
    const wasGenerated = existing.includes(SKILLFILE_MARKER);
    if (!wasGenerated) {
      console.error(
        `AGENTS.md already exists and wasn't generated by skillfile.\n` +
          `Refusing to overwrite a hand-written file. Re-run with --force to overwrite anyway.`
      );
      process.exitCode = 1;
      return null;
    }
  }

  const { scan, paths } = writeAll(cwd);
  console.log(`skillfile: generated context for "${scan.repoName}"\n`);
  console.log(`  ${path.relative(cwd, paths.agentsMd)}`);
  console.log(`  ${path.relative(cwd, paths.skillMd)}`);
  console.log(`  ${path.relative(cwd, paths.skillfileManifest)}\n`);
  console.log(`Commit these files. Run \`skillfile update\` after structural changes,`);
  console.log(`or \`skillfile check\` in CI to catch drift before it merges.`);
  return { scan, paths };
}

function update(cwd) {
  const { scan, paths } = writeAll(cwd);
  console.log(`skillfile: updated context for "${scan.repoName}"`);
  return { scan, paths };
}

function check(cwd) {
  const manifestPath = path.join(cwd, 'SKILLFILE.md');
  if (!fs.existsSync(manifestPath)) {
    console.error('skillfile: not initialized in this repo. Run `skillfile init` first.');
    process.exitCode = 2;
    return;
  }

  const existing = fs.readFileSync(manifestPath, 'utf8');
  const hashMatch = existing.match(/source-hash:\s*([a-f0-9]+)/);
  const existingHash = hashMatch ? hashMatch[1] : null;

  const scan = scanRepo(cwd);
  const freshHash = contentFingerprint(scan);

  if (existingHash === freshHash) {
    console.log('skillfile: up to date.');
    process.exitCode = 0;
    return;
  }

  console.error(
    `skillfile: AGENTS.md / SKILL.md are stale (repo has drifted since last generation).\n` +
      `Run \`skillfile update\` and commit the result.`
  );
  process.exitCode = 1;
}

module.exports = { init, update, check, outputPaths, SKILLFILE_MARKER };
