const { stableHash } = require('./hash');

/** Fields that reflect real repo state — used for the freshness hash.
 * `scannedAt` is deliberately excluded: it changes on every run and would
 * make `check` report "stale" even when nothing actually changed. */
function contentFingerprint(scan) {
  const { scannedAt, ...rest } = scan;
  return stableHash(rest);
}

function renderScriptsList(scripts) {
  const entries = Object.entries(scripts || {});
  if (entries.length === 0) return '_No scripts declared._';
  return entries.map(([name, cmd]) => `- \`${name}\`: \`${cmd}\``).join('\n');
}

function renderDirList(dirs) {
  if (!dirs.length) return '_No subdirectories._';
  return dirs.map((d) => `- \`${d}/\``).join('\n');
}

function renderToolingList(tooling) {
  const lines = [];
  if (tooling.hasCI) lines.push('- CI configured (`.github/workflows`)');
  if (tooling.hasTests) lines.push('- Has a dedicated test directory');
  if (tooling.hasTypeScript) lines.push('- TypeScript (`tsconfig.json`)');
  if (tooling.hasLinter) lines.push('- Linter configured');
  if (tooling.hasDocker) lines.push('- Dockerized');
  return lines.length ? lines.join('\n') : '_No tooling markers detected._';
}

/** Plain markdown, no frontmatter — the AGENTS.md convention read natively
 * by Codex, Cursor, Copilot, Gemini CLI, Aider, Windsurf, and 20+ other
 * agent tools. This is the cross-agent half of the output. */
function renderAgentsMd(scan) {
  const { repoName, description, language, packageManager, scripts, topLevelDirs, tooling, git } = scan;

  return `<!-- skillfile:generated -->
# ${repoName}

${description || '_No description found in package manifest or README._'}

## Stack

- Language: ${language}
${packageManager ? `- Package manager: ${packageManager}` : ''}

## Commands

${renderScriptsList(scripts)}

## Structure

${renderDirList(topLevelDirs)}

## Tooling

${renderToolingList(tooling)}
${
  git
    ? `
## Recent activity

Branch: \`${git.branch || 'unknown'}\`
${git.recentCommits.map((c) => `- ${c}`).join('\n')}
`
    : ''
}
---
Generated by [skillfile](https://skillfile.dev) — run \`npx skillfile update\` after structural changes, or \`npx skillfile check\` in CI to catch drift.
`;
}

/** Anthropic SKILL.md format: YAML frontmatter (name + description) is what
 * Claude reads to decide when to load the skill; the body is the same
 * content as AGENTS.md so both formats stay in sync from one scan. */
function renderSkillMd(scan) {
  const { repoName, description } = scan;
  const oneLineDescription = (description || `Repository context for ${repoName}.`).replace(/"/g, "'");

  return `---
name: ${repoName}
description: "${oneLineDescription} Auto-generated by skillfile — use this for build/test commands, structure, and recent activity before exploring the repo manually."
---

${renderAgentsMd(scan)}`;
}

/** Cursor reads .mdc rules with their own frontmatter; alwaysApply keeps the
 * repo context in every request rather than waiting for a filename match. */
function renderCursorMdc(scan) {
  const description = (scan.description || `Repository context for ${scan.repoName}.`).replace(/"/g, "'");

  return `---
description: "${description}"
alwaysApply: true
---

${renderAgentsMd(scan)}`;
}

/** Format name → renderer. The contract (tools.json): the same `format`
 * guarantees byte-identical output, so targets sharing a format share these
 * exact bytes at different destinations. scripts/check-tools.js fails CI if
 * this registry and tools.json disagree. */
const RENDERERS = {
  'agents-md': renderAgentsMd,
  'claude-skill': renderSkillMd,
  'cursor-mdc': renderCursorMdc,
};

/** skillfile's own manifest — the branded, unremovable artifact (deleting
 * it means losing the freshness hash the whole loop depends on). Human and
 * agent readable; also the file `check` diffs against. The `tools` list is
 * load-bearing: a bare `update`/`check` in CI reads it back to know which
 * opt-in targets this repo enabled. */
function renderSkillfileManifest(scan, targets) {
  const fingerprint = contentFingerprint(scan);
  const enabled = targets.map((t) => t.id);
  return `---
generated-by: skillfile.dev
generated-at: ${scan.scannedAt}
source-hash: ${fingerprint}
tools: [${enabled.join(', ')}]
---

# SKILLFILE.md

This repo's agent context is generated by [skillfile](https://skillfile.dev) from a deterministic scan — no LLM calls, no API key required.

${targets.map((t) => `- \`${t.dest}\` — ${t.label}`).join('\n')}

## Keeping this fresh

- \`npx skillfile update\` — re-scan and rewrite both files (free, no LLM call)
- \`npx skillfile check\` — exits non-zero if the repo has drifted since the last generation; wire into CI so a stale context file fails the build, the same way a stale lockfile would

Source hash: \`${fingerprint}\` (changes when scripts, dependencies, structure, or recent commits change — not on every run)
`;
}

module.exports = {
  renderAgentsMd,
  renderSkillMd,
  renderCursorMdc,
  renderSkillfileManifest,
  contentFingerprint,
  RENDERERS,
};
